---
title: Integrated ATAC-seq and RNA-seq analysis for SCLC
author: CCBR
date: 2024-07-05
format:
    html:
        theme: [default]
        embed-resources: true
        code-fold: true
params:
  atac_rna_tsv:   "output/rowbind_logfc/concat.atac_rna.tsv"
  atac_rna_venn:  "output/join_atac_rna/joined_atac_rna.log"
  set_counts_tsv: "output/rowbind_count/concat.set_counts.tsv"
  clusterprofiler_rdata: "output/clusterprofiler/clusterProfiler.RData"
  chromvar_rdata:   "output/chromvar/chromVAR.results.RData"
  top_tfs_hint: 'output_2/calc_rank_score/top_TFs_HINT.csv'
  tf_ranks_hint: 'output_2/calc_rank_score/tf_rank_HINT.tsv'
---

```{r setup}
#| message: false
#| warning: false
library(tidyverse)
library(broom)
library(ggVennDiagram)
library(glue)
library(knitr)
library(patchwork)
library(plotly)
library(rlang)
library(scales)
library(tidyverse)
theme_sovacool <- ggplot2::theme_bw() +
    ggplot2::theme(
      legend.margin = ggplot2::margin(0, 0, 0, 0, unit = "pt"),
      legend.box.margin = ggplot2::margin(0, 0, 0, 0, unit = "pt"),
      panel.spacing = unit(1, 'lines'),
      plot.margin = ggplot2::margin(0, 0, 0, 0, unit = "pt"),
      strip.background = element_blank(),
      strip.placement = 'outside'
    )
theme_set(theme_sovacool)
set.seed(20240326)

```


## Top TFs

```{r TFs_HINT}
#| message: false
#| fig-width: 10
#| fig-height: 6.5
plot_heatmap_sqr <- function(dat = top_tfs_hint,
                             value_column = A_diff,
                             cluster = 'c1') {
    dat %>%
        filter(cluster_id == cluster) %>%
        mutate(gene_name = fct_reorder(as_factor(gene_name), TF_rank)) %>%
        ggplot(aes(x = gene_name, y = 1, # y = diff,
                   fill = {{ value_column }})) +
        geom_tile() +
        {
            if (cluster == 'c1') {
                labs(y = quo_name(enquo(value_column)), x = "")
            } else {
                labs(y = "", x = "")
            }
        } +
        theme(
            axis.text.x = element_text(
                angle = 60,
                vjust = 1,
                hjust = 1
            ),
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank(),
        )
}

plot_heatmap_col <- function(top_tfs_hint = top_tfs_hint,
                             cluster = 'c1', show_legend = FALSE) {
    ((
        plot_heatmap_sqr(top_tfs_hint, outdegree, cluster) +
            colorspace::scale_fill_continuous_diverging(palette = 'Blue-Red') +
            theme(axis.text.x = element_blank()) +
            labs(title = cluster)
    ) /
        (
            plot_heatmap_sqr(top_tfs_hint, expression, cluster) +
                colorspace::scale_fill_continuous_diverging(palette = 'Green-Orange') +
                theme(axis.text.x = element_blank(), strip.text = element_blank())
        ) /
        (
            plot_heatmap_sqr(top_tfs_hint, accessibility, cluster) +
                colorspace::scale_fill_continuous_diverging(palette = 'Purple-Green')  +
                theme(strip.text = element_blank(), axis.text.x = element_blank())
        ) /
        (
            plot_heatmap_sqr(top_tfs_hint, TF_rank, cluster) +
                scale_fill_distiller(palette = 'Greys') +
                theme(strip.text = element_blank(),
                      legend.position = 'none')
        ) & {if (isFALSE(show_legend)) theme(legend.position = 'none')}
    )  +
        plot_layout(heights = c(1,1,1,0.33))
}

top_tfs_hint <- read_csv(params$top_tfs_hint)

plot_heatmap_col(top_tfs_hint, cluster = 'c1') |
    plot_heatmap_col(top_tfs_hint, cluster = 'c2') |
    plot_heatmap_col(top_tfs_hint, cluster = 'c3', show_legend = TRUE)
```


## check whether ASCL1 & NEUROD1 show up in C3

```{r c3-check}
all_tfs <- read_tsv(params$tf_ranks_hint)
all_tfs %>% filter(cluster_id == 'c3', str_detect(gene_name,'ASCL') | str_detect(gene_name,'NEURO'))
```

```{r c3-tracing}
# get TSS gene names that contained ASCL1 or NEUROD1 motifs identified in peaks
motif_dat <- read_tsv('output_2/peaks_genes_motifs/peaks_genes_motifs.tsv')
c3_dat <- motif_dat %>%
    filter(cluster == 'cluster3', str_detect(TF_list,'ASCL1') | str_detect(TF_list,'NEUROD1')) %>%
    separate_longer_delim(TF_list, delim = ',') %>%
    rename(TF_name = TF_list) %>%
    filter(TF_name == 'ASCL1' | TF_name == 'NEUROD1')
tss_genes <- c3_dat %>% select(TSS_gene_name, peak_coord) %>% distinct()

# these genes were correlated
corr_dat <- read_tsv('output_2/correlations/gene_peak_corr.tsv')
head(corr_dat %>% left_join(tss_genes))

# and the correlations pass the FDR filter
corr_dat_filt <- read_tsv('output_2/filter_corr_tsv/gene_peak_corr_filt.tsv')
corr_dat_filt %>% left_join(tss_genes)

# they show up in network outdegree data
outdegree_dat <- read_tsv('output_2/network_outdegree/TF_outdegree.tsv')
outdegree_dat %>% filter(TF_name %in% c('ASCL1', 'NEUROD1'))

# they're in the log2FC RNAseq data
datasheet <- "assets/datasheet.csv"
diff_dat <- read_csv(datasheet) %>%
  mutate(cluster_id = glue('c{cluster}')) %>%
  pmap(\(cluster_id, rna, atac, cluster) {
      read_tsv(rna) %>%
          #rename(gene_name = `...1`) %>% # object not found error?!
          mutate(cluster_id = cluster_id)
  }) %>%
  bind_rows()
colnames(diff_dat)[1] <- 'gene_name'
diff_dat %>% filter(cluster_id == 'c3', gene_name %in% c('ASCL1', 'NEUROD1'))

# ! neither show up in the chromvar data
infile_chromvar <- "output/chromvar/chromVAR.results.tsv"
chromvar_dat <- read_tsv(infile_chromvar)
chromvar_dat %>% filter(str_detect(motif, 'ASCL1') | str_detect(motif, 'NEUROD1'))

# chromvar uses JASPAR2016 (386 motifs), while RGT HINT uses JASPAR2020 (746 motifs)
library(chromvar)
?getJasparMotifs
motifs <- chromvar::getJasparMotifs()
length(motifs)
```


```{r chromvar-trace}
# adapted from https://github.com/GreenleafLab/chromVAR/blob/0f27fcc8463d537d770f164a55f949701beb6add/R/motifs.R
getJasparMotifs_ccbr <- function(species = "Homo sapiens",
                                 collection = "CORE",
                                 jaspar_db = JASPAR2016::JASPAR2016,
                                 ...) {
  opts <- list()
  opts["species"] <- species
  opts["collection"] <- collection
  opts <- c(opts, list(...))
  out <- TFBSTools::getMatrixSet(jaspar_db, opts)
  if (!isTRUE(all.equal(TFBSTools::name(out), names(out))))
    names(out) <- paste(names(out), TFBSTools::name(out), sep = "_")
  return(out)
}
motifs_2016 <- getJasparMotifs_ccbr()
length(motifs_2016)
motifs_2020 <- getJasparMotifs_ccbr(jaspar_db = JASPAR2020::JASPAR2020)
length(motifs_2020)
names(motifs_2020) %>% Filter(\(x) str_detect(x, "ASCL1") | str_detect(x, 'NEUROD1'), .)
```
