---
title: Alternative TF rank visualizations
author: CCBR
date: 2024-12-05
format: 
    html:
        theme: [default]
        embed-resources: true
        code-fold: true
params:
  tf_rank_filename: "output_2/calc_rank_score/tf_rank_HINT.tsv"
  top_n: 25
  tf_within_cluster: 'output_2/calc_rank_score/tf_rank_within_clusters.csv'
---


```{r setup}
#| message: false
#| warning: false
library(here)
library(broom)
library(glue)
library(knitr)
library(patchwork)
library(plotly)
library(rlang)
library(scales)
library(tidyverse)
theme_sovacool <- ggplot2::theme_bw() +
    ggplot2::theme(
      legend.margin = ggplot2::margin(0, 0, 0, 0, unit = "pt"),
      legend.box.margin = ggplot2::margin(0, 0, 0, 0, unit = "pt"),
      panel.spacing = unit(1, 'lines'),
      plot.margin = ggplot2::margin(0, 0, 0, 0, unit = "pt"),
      strip.background = element_blank(),
      strip.placement = 'outside',
      panel.grid.major.y = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank()
    )
theme_set(theme_sovacool)
set.seed(20241205)

clean_dat <- function(dat) {
 dat %>% 
    filter(TF_rank <= params$top_n) %>% 
    pivot_longer(
        c(rank_A_diff, rank_O_diff, rank_E_diff),# TF_rank),
        names_to = 'metric',
        values_to = 'rank'
    ) %>%
    mutate(
        metric = case_when(
            metric == 'rank_A_diff' ~ 'Accessibility',
            metric == 'rank_E_diff' ~ 'Expression',
            metric == 'rank_O_diff' ~ 'Outdegree',
            #metric == 'TF_rank' ~ 'Overall TF rank',
            TRUE ~ NA_character_
        ) %>% fct_relevel(
            c('Outdegree', 'Expression', 'Accessibility')#, 'Overall TF rank')
        )
    ) 
}
dat <- read_tsv(here(params$tf_rank_filename)) %>% clean_dat()

dat_within_cluster <- read_csv(here(params$tf_within_cluster)) %>% 
    rename(rank_A_diff = rank_A_score,
           rank_E_diff = rank_E_score,
           rank_O_diff = rank_O_score,
           gene_name = TF_name)
n_TFs <- dat_within_cluster %>% pull(gene_name) %>% unique() %>% length()
dat_within_cluster <- dat_within_cluster %>% clean_dat()
```

## Top TFs distinguishing clusters

Using original methods from Fig. 3 of Tang _et al._

Smaller bar indicates lower rank, which indicates higher outdegree, expression, 
or accessibility score relative to other TFs within the cluster.
Smaller bar = more important TF.

```{r plot_rank_stacked_orig}
#| message: false

plot_cluster_col <- function(dat, cluster) {
    dat_cluster <- dat %>% filter(cluster_id == cluster)
    genes_order <- dat_cluster %>% arrange(desc(TF_rank)) %>% pull(gene_name) %>% unique()
    dat_cluster %>%
        mutate(gene_name = factor(gene_name, levels = genes_order)) %>%
        ggplot(aes(x = rank, y = gene_name, fill = metric)) +
        geom_col() +
        scale_fill_brewer(palette = 'Dark2') +
        guides(fill = guide_legend(title = 'Rank'), reverse = TRUE) +
        labs(title = cluster, x = '', y = '') +
        { if (cluster != 'c2') theme(legend.position = 'none') else theme(legend.position = 'bottom') }
}
wrap_plots(lapply(c('c1','c2','c3'), function(x) plot_cluster_col(dat, x)))
```


## Top TFs within clusters

```{r plot_rank_stacked_within-cluster}
#| message: false
c('c1', 'c2', 'c3') %>%
    lapply(function(cluster) {
        plot_cluster_col(dat_within_cluster, cluster)
    }) %>%
    wrap_plots()
```
