---
title: 'integrated differential ATACseq and RNAseq'
date: today
engine: knitr
format:
    html:
        self-contained: true
        toc: true
        code-fold: true
params:
  cpus: 1
  artifact_dir: NULL
  input_dir: NULL
  meta: NULL
  atac_rna_tsv: "output/rowbind/concat.atac_rna.tsv"
  atac_rna_venn: "output/join_atac_rna/joined_atac_rna.log"
---

```{r setup}
#| message: false
library(broom)
library(dplyr)
library(ggplot2)
library(ggVennDiagram)
library(glue)
library(knitr)
library(plotly)
library(readr)
library(stringr)
library(tidyr)
theme_set(theme_bw())
```



```{r read}
#| message: false
dat <- read_tsv(params$atac_rna_tsv) %>% 
    mutate(cluster_id = as.factor(cluster_id))
```


## Differential ATAC & RNAseq 

### Overlapping differential genes from ATAC & RNAseq

```{r plot_venn}
#| message: false
v <- read_delim(params$atac_rna_venn, delim = ':\t', 
           col_names = c('set','genes')) %>% 
    pivot_wider(names_from = set, values_from = genes) %>% 
    unlist()

venn_dat <- list(
    RNAseq = identity_transformer(glue("1:{v[['RNAseq']]}")),
    ATACseq = identity_transformer(glue("{v[['RNAseq']]-v[['joined']]}:{v[['RNAseq']]+v[['ATACseq']]+v[['joined']]}"))
)

Venn(venn_dat) %>% 
    process_data(shape_id = "201") %>% 
    plot_venn() +
    scale_fill_distiller(palette = 'YlGnBu', direction = 1) +
    theme(legend.position = 'none')

```


### correlation

```{r plot_corr_line}
cor_logfc <- dat %>% 
    group_by(cluster_id) %>% 
    do(tidy(cor.test(.$log2FoldChange_atac, .$log2FoldChange_rna, 
                     method = "spearman")))
kable(cor_logfc)
lm_logfc <- dat %>% group_by(cluster_id) %>% 
  do(tidy(lm(log2FoldChange_atac ~ log2FoldChange_rna, .)))

min_max <- list(
  min = ~min(.x, na.rm = TRUE), 
  max = ~max(.x, na.rm = TRUE)
)
abs_max <- dat %>% 
    summarize(across(starts_with('log2FoldChange'), min_max)) %>% 
    as.list() %>% unname() %>% unlist() %>% abs() %>% max()
corr_line_plot <- dat %>% 
    mutate(across(starts_with('log2FoldChange'), ~ round(., 2))) %>% 
    ggplot(aes(y = log2FoldChange_atac, x = log2FoldChange_rna,
               color = cluster_id, group = cluster_id, 
               text = glue('gene name:\t{gene_name}', 
                           'cluster:\t{cluster_id}',
                           'ATAC log2(FC):\t{log2FoldChange_atac}',
                           'RNA log2(FC):\t{log2FoldChange_rna}',
                           .sep = '\n')
               )
           ) +
    geom_hline(yintercept = 0, linetype = 'dashed', color = 'darkgrey') +
    geom_vline(xintercept = 0, linetype = 'dashed', color = 'darkgrey') +
    geom_point(alpha = 0.7) +
    #geom_smooth(method=lm, se=FALSE) +
    scale_color_viridis_d() +
    guides(color = guide_legend(title = 'cluster')) +
    lims(x = c(-abs_max, abs_max), y = c(-abs_max, abs_max)) +
    labs(y = 'ATAC log2(FC)', x = 'RNA log2(FC)')
ggplotly(corr_line_plot, tooltip = 'text')
```


