---
title: Integrated ATAC-seq and RNA-seq analysis for SCLC
author: CCBR
date: 2024-07-12
format: 
    html:
        theme: [default]
        embed-resources: true
        code-fold: true
params:
  top_tfs_hint: 'output_2/calc_rank_score/top_TFs_HINT.csv'
  tf_ranks_hint: 'output_2/calc_rank_score/tf_rank_HINT.tsv'
---

```{r setup}
#| message: false
#| warning: false
library(tidyverse)
library(broom)
library(ggVennDiagram)
library(glue)
library(knitr)
library(patchwork)
library(plotly)
library(rlang)
library(scales)
library(tidyverse)
theme_sovacool <- ggplot2::theme_bw() +
    ggplot2::theme(
      legend.margin = ggplot2::margin(0, 0, 0, 0, unit = "pt"),
      legend.box.margin = ggplot2::margin(0, 0, 0, 0, unit = "pt"),
      panel.spacing = unit(1, 'lines'),
      plot.margin = ggplot2::margin(0, 0, 0, 0, unit = "pt"),
      strip.background = element_blank(),
      strip.placement = 'outside'
    )
theme_set(theme_sovacool)
set.seed(20240326)

```


## Top TFs distinguishing clusters

Using the methods from Fig. 3 of Tang _et al._

```{r TFs_HINT}
#| message: false
#| fig-width: 10
#| fig-height: 6.5
plot_heatmap_sqr <- function(dat = top_tfs_hint,
                             value_column = A_diff,
                             cluster = 'c1') {
    dat %>%
        filter(cluster_id == cluster) %>%
        mutate(gene_name = fct_reorder(as_factor(gene_name), TF_rank)) %>%
        ggplot(aes(x = gene_name, y = 1, # y = diff,
                   fill = {{ value_column }})) +
        geom_tile() +
        {
            if (cluster == 'c1') {
                labs(y = quo_name(enquo(value_column)), x = "")
            } else {
                labs(y = "", x = "")
            }
        } +
        theme(
            axis.text.x = element_text(
                angle = 60,
                vjust = 1,
                hjust = 1
            ),
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank(),
        )
}

plot_heatmap_col <- function(top_tfs_hint,
                             cluster = 'c1', show_legend = FALSE) {
    ((
        plot_heatmap_sqr(top_tfs_hint, outdegree, cluster) +
            colorspace::scale_fill_continuous_diverging(palette = 'Blue-Red') +
            theme(axis.text.x = element_blank()) +
            labs(title = cluster)
    ) /
        (
            plot_heatmap_sqr(top_tfs_hint, expression, cluster) +
                colorspace::scale_fill_continuous_diverging(palette = 'Green-Orange') +
                theme(axis.text.x = element_blank(), strip.text = element_blank())
        ) /
        (
            plot_heatmap_sqr(top_tfs_hint, accessibility, cluster) +
                colorspace::scale_fill_continuous_diverging(palette = 'Purple-Green')  +
                theme(strip.text = element_blank(), axis.text.x = element_blank())
        ) /
        (
            plot_heatmap_sqr(top_tfs_hint, TF_rank, cluster) +
                scale_fill_distiller(palette = 'Greys') +
                theme(strip.text = element_blank(),
                      legend.position = 'none')
        ) & {if (isFALSE(show_legend)) theme(legend.position = 'none')} 
    )  + 
        plot_layout(heights = c(1,1,1,0.33))
}
plot_heatmap_grid <- function(dat) {
    plot_heatmap_col(dat, cluster = 'c1') |
    plot_heatmap_col(dat, cluster = 'c2') |
    plot_heatmap_col(dat, cluster = 'c3', show_legend = TRUE)
}

top_tfs_hint <- read_csv(params$top_tfs_hint)
plot_heatmap_grid(top_tfs_hint)
```


### check whether ASCL1 & NEUROD1 show up in C3

```{r check-c3}
#| message: false
all_tfs <- read_tsv(params$tf_ranks)
all_tfs %>% 
    filter(str_detect(gene_name,'ASCL1') | str_detect(gene_name,'NEUROD1')) %>% 
    kable()
```

## rank TFs within clusters

Rather than ranking TFs that _distinguish_ a cluster from the others,
let's see a ranking of the TFs within each cluster.

```{r TFs_within_clusters}
#| message: false
#| fig-width: 10
#| fig-height: 6.5
infile_matched <- 'output_2/match_atac_rna_ids/matched_sample_ids.tsv'
infile_rna_expr <- 'data/rna_counts_normalized.csv'
infile_clusters <- "assets/cluster_membership.tsv"
infile_chromvar <- "output_2/chromvar/chromVAR.results.tsv"
infile_outdegree <- "output_2/network_outdegree/TF_outdegree.tsv"

sample_matches <- read_tsv(infile_matched) %>% select(atac_sample_id, rna_sample_id)

cluster_membership <- read_tsv(infile_clusters) %>%
    rename(cluster_id = clusterName, sample_id = sampleName) %>% 
    right_join(sample_matches, by = c('sample_id' = 'atac_sample_id')) %>% 
    filter(!is.na(sample_id), !is.na(rna_sample_id))

cluster_counts <- cluster_membership %>%
    dplyr::count(cluster_id)

cluster_membership %<>%
    left_join(cluster_counts, by = "cluster_id") %>%
    select(-bam)
chromvar_dat <- read_tsv(infile_chromvar)

atac_scores <- chromvar_dat %>%
    pivot_longer(ends_with(".bam"),
      names_to = "sample_id", values_to = "z_score"
    ) %>%
    mutate(sample_id = str_replace_all(sample_id, ".sorted.dedup.bam", "")) %>%
    left_join(cluster_membership, relationship = 'many-to-many') %>% 
    select(name, sample_id, z_score, cluster_id, n) %>%
    rename(TF_name = name) %>% 
    separate_longer_delim(TF_name, '::') %>% 
    group_by(cluster_id, TF_name) %>% 
    summarize(A_score = mean(z_score))

rna_scores <- read_csv(infile_rna_expr) %>% 
    rename(TF_name = 'hgnc_symbol') %>% 
    pivot_longer(-TF_name, names_to = 'rna_sample_id', values_to = 'rna_count_norm') %>% 
    left_join(cluster_membership, relationship = 'many-to-many') %>% 
    group_by(TF_name, cluster_id) %>% 
    summarize(E_score = mean(rna_count_norm))

outdegree_scores <- read_tsv(infile_outdegree) %>%
    filter(!is.na(sample_id)) %>%
    left_join(cluster_membership, relationship = 'many-to-many') %>% 
    group_by(TF_name, cluster_id) %>% 
    summarize(O_score = mean(outdegree))


dat_joined <- full_join(atac_scores, rna_scores, 
                        by = c('TF_name', 'cluster_id')) %>%
    full_join(outdegree_scores, by = c('TF_name', 'cluster_id')) %>% 
    filter(if_all(everything(), ~ !is.na(.x)))

rank_col <- function(dat,
                     value_col = A_diff,
                     group_col = cluster_id) {
    dat %>%
        group_by({{ group_col }}) %>%
        arrange(desc({{ value_col }})) %>%
        mutate("rank_{{value_col}}" := row_number())
}

tf_ranks_clusters <- dat_joined %>% 
    rank_col(value_col = A_score) %>% 
    rank_col(value_col = E_score) %>% 
    rank_col(value_col = O_score) %>%
    mutate(rank_sum = rank_A_score + rank_E_score + rank_O_score) %>%
    group_by(cluster_id) %>%
    arrange(rank_sum) %>%
    mutate(TF_rank = row_number()) %>%
    arrange(TF_rank)

# ASCL1 & NEUROD1 are present
tf_ranks_clusters %>% filter(TF_name == 'ASCL1' | TF_name == 'NEUROD1') %>% 
    kable()

tf_ranks_clusters %>% 
    filter(TF_rank <= 25) %>% 
    rename(outdegree = O_score,
           expression = E_score,
           accessibility = A_score,
           gene_name = TF_name) %>% 
    plot_heatmap_grid()
```

